const mongoose = require("mongoose");
const Team   = require("../models/Team");
const User   = require("../models/User");
const Note   = require("../models/Note");
const { sendTeamInvite } = require("../utils/emailUtils");
const logger = require("../utils/logger");
const { logAction } = require("./activityLogService");

function notFound(msg = "Team not found.") { const e = new Error(msg); e.statusCode = 404; return e; }
function forbidden(msg = "Access denied.") { const e = new Error(msg); e.statusCode = 403; return e; }

async function getMyTeams(userId) {
  return Team.find({
    $or: [{ ownerId: userId }, { "members.userId": userId }],
    isArchived: false,
  })
    .populate("ownerId", "name email avatar")
    .populate("members.userId", "name email avatar")
    .sort({ createdAt: -1 })
    .lean();
}

async function getTeamById(teamId) {
  return Team.findById(teamId)
    .populate("ownerId", "name email avatar")
    .populate("members.userId", "name email avatar");
}

async function createTeam(userId, data) {
  const team = await Team.create({
    ...data,
    ownerId: userId,
    members: [{ userId, role: "owner", joinedAt: new Date() }],
  });
  return team;
}

async function updateTeam(teamId, userId, updates) {
  const team = await Team.findById(teamId);
  if (!team) throw notFound();
  if (!team.isAdmin(userId)) throw forbidden("Team admin required.");
  const allowed = ["name", "description", "color", "avatar"];
  allowed.forEach((k) => { if (updates[k] !== undefined) team[k] = updates[k]; });
  await team.save();
  return team;
}

async function deleteTeam(teamId, userId) {
  const team = await Team.findById(teamId);
  if (!team) throw notFound();
  if (!team.ownerId.equals(userId)) throw forbidden("Only the team owner can delete the team.");
  team.isArchived = true;
  await team.save();
  // Detach team notes — they become personal notes of their original authors
  await Note.updateMany({ teamId: team._id }, { $set: { teamId: null } });
}

async function inviteMember(team, inviterId, { email, role = "member" }) {
  const inviter = await User.findById(inviterId);
  if (!inviter) throw notFound("Inviter not found.");

  const existingUser = await User.findOne({ email });

  // Check both members array AND owner
  if (existingUser) {
    const isOwner  = team.ownerId.equals(existingUser._id);
    const isMember = team.isMember(existingUser._id);
    if (isOwner || isMember) {
      const e = new Error("This user is already a member of the team."); e.statusCode = 409; throw e;
    }
  }

  // Check for active (non-expired, non-accepted) pending invite
  const alreadyInvited = team.pendingInvites.some(
    (i) => i.email === email && !i.accepted && new Date(i.expiresAt) > new Date()
  );
  if (alreadyInvited) {
    const e = new Error("An active invitation has already been sent to this email."); e.statusCode = 409; throw e;
  }

  team.pendingInvites.push({ email, role, invitedBy: inviterId });
  await team.save();

  // The last pushed invite has the uuid token generated by schema default
  const savedInvite = team.pendingInvites[team.pendingInvites.length - 1];
  const inviteLink  = `${process.env.FRONTEND_URL || "http://localhost:5173"}/accept-invite?token=${savedInvite.token}`;

  // PERF FIX: Send email in background — don't block the API response
  // This makes the invite button respond instantly instead of waiting 2-3 sec for email
  sendTeamInvite({ toEmail: email, inviterName: inviter.name, teamName: team.name, inviteLink })
    .then(result => {
      if (!result.sent) logger.warn(`Invite email not delivered to ${email}: ${result.reason}`);
    })
    .catch(err => {
      logger.warn(`Invite email failed for ${email}: ${err.message}`);
    });

  // Activity log: member invited
  await logAction({
    teamId: team._id,
    actorId: inviterId,
    actorName: inviter.name,
    action: "member.invite",
    description: `invited ${email} as ${role}`,
    targetType: "member",
    targetName: email,
    metadata: { email, role },
  }).catch(() => {});

  // Return immediately — email is being sent in background
  return { invite: { email, role, inviteLink }, existingAccount: !!existingUser };
}

async function acceptInvite(token, userId) {
  const user = await User.findById(userId);
  if (!user) throw notFound("User not found.");

  // Use $elemMatch to correctly query nested array conditions together
  const team = await Team.findOne({
    pendingInvites: {
      $elemMatch: {
        token,
        accepted:  false,
        expiresAt: { $gt: new Date() },
      },
    },
  });

  if (!team) {
    const e = new Error("Invite not found or has expired. Ask your team admin to resend it.");
    e.statusCode = 404; throw e;
  }

  const invite = team.pendingInvites.find((i) => i.token === token);

  if (invite.email !== user.email) {
    const e = new Error("This invite was sent to a different email address."); e.statusCode = 403; throw e;
  }

  if (team.isMember(userId) || team.ownerId.equals(userId)) {
    const e = new Error("You are already a member of this team."); e.statusCode = 409; throw e;
  }

  team.members.push({ userId, role: invite.role, joinedAt: new Date() });
  invite.accepted = true;
  await team.save();

  // Activity log: member joined
  await logAction({
    teamId: team._id,
    actorId: userId,
    actorName: user.name,
    action: "member.join",
    description: `joined the team as ${invite.role}`,
    targetType: "member",
    targetId: userId,
    targetName: user.name,
    metadata: { email: user.email, role: invite.role },
  }).catch(() => {});

  // Return populated team
  await team.populate("ownerId", "name email avatar");
  await team.populate("members.userId", "name email avatar");
  return team;
}

async function removeMember(teamId, requesterId, targetUserId) {
  const team = await Team.findById(teamId);
  if (!team) throw notFound();

  const isSelf  = requesterId.toString() === targetUserId.toString();
  const isAdmin = team.isAdmin(requesterId);

  if (!isSelf && !isAdmin) throw forbidden("You cannot remove other members.");
  if (team.ownerId.equals(targetUserId)) {
    const e = new Error("The team owner cannot be removed. Transfer ownership first."); e.statusCode = 400; throw e;
  }

  // Capture target name before removal for the log
  let targetName = "member";
  try {
    const target = await User.findById(targetUserId).select("name").lean();
    targetName = target?.name || "member";
  } catch { /* best-effort */ }

  team.members = team.members.filter((m) => !m.userId.equals(targetUserId));
  await team.save();

  await logAction({
    teamId: team._id,
    actorId: requesterId,
    action: "member.remove",
    description: `${isSelf ? "left" : "removed"} ${isSelf ? "the team" : targetName}`,
    targetType: "member",
    targetId: targetUserId,
    targetName,
    metadata: { isSelf },
  }).catch(() => {});
}

async function updateMemberRole(teamId, requesterId, targetUserId, role) {
  const team = await Team.findById(teamId);
  if (!team) throw notFound();
  if (!team.ownerId.equals(requesterId)) throw forbidden("Only the team owner can change roles.");
  if (team.ownerId.equals(targetUserId)) {
    const e = new Error("Cannot change the owner's role."); e.statusCode = 400; throw e;
  }
  const member = team.members.find((m) => m.userId.equals(targetUserId));
  if (!member) { const e = new Error("Member not found."); e.statusCode = 404; throw e; }
  const previousRole = member.role;
  member.role = role;
  await team.save();

  let targetName = "member";
  let actorName  = "someone";
  try {
    const [target, actor] = await Promise.all([
      User.findById(targetUserId).select("name").lean(),
      User.findById(requesterId).select("name").lean(),
    ]);
    targetName = target?.name || "member";
    actorName  = actor?.name || "someone";
  } catch { /* best-effort */ }

  await logAction({
    teamId: team._id,
    actorId: requesterId,
    actorName,
    action: "member.role",
    description: `changed ${targetName}'s role from ${previousRole} to ${role}`,
    targetType: "member",
    targetId: targetUserId,
    targetName,
    metadata: { previousRole, newRole: role },
  }).catch(() => {});

  // REAL-TIME FIX #2: Broadcast role change to all team members via Socket.io
  // so their member lists update INSTANTLY without a page reload. Previously,
  // a promoted member had to refresh the page to see their new "Admin" badge.
  try {
    const io = require("../app").get("io");
    if (io) {
      io.to(`team:${teamId}`).emit("member:roleUpdated", {
        teamId: teamId.toString(),
        memberId: targetUserId.toString(),
        previousRole,
        role,
        updatedBy: requesterId.toString(),
        updatedByName: actorName,
      });
    }
  } catch { /* io not yet attached — skip */ }

  // FIX: Re-fetch the team with populated members before returning. Without
  // this, the response contains `members[].userId` as raw ObjectIds (no
  // name/email), which would break the frontend's optimistic cache update
  // (it would overwrite the populated cached team with unpopulated data,
  // making the badge revert and the member row unable to render the name).
  const populatedTeam = await Team.findById(teamId)
    .populate("ownerId", "name email avatar")
    .populate("members.userId", "name email avatar");
  return populatedTeam;
}

async function cancelInvite(teamId, requesterId, email) {
  const team = await Team.findById(teamId);
  if (!team) throw notFound();
  if (!team.isAdmin(requesterId)) throw forbidden("Team admin required.");
  team.pendingInvites = team.pendingInvites.filter((i) => i.email !== email);
  await team.save();
}

// COMBINED FIX #3: Update a member's status (active/inactive/suspended).
// FIX #3 (v2): Removed — member status field no longer exists in the schema.
// Only role (owner/admin/member) is used to describe a member's standing.

// PERF FIX: Use Promise.all for parallel DB queries in getTeamStats
async function getTeamStats(teamId) {
  const [noteCount, team] = await Promise.all([
    Note.countDocuments({ teamId: new mongoose.Types.ObjectId(teamId), isDeleted: false }),
    Team.findById(teamId).select("members"),
  ]);
  return { noteCount, memberCount: team?.members.length || 0 };
}

module.exports = {
  getMyTeams, getTeamById, createTeam, updateTeam, deleteTeam,
  inviteMember, acceptInvite, removeMember, updateMemberRole, cancelInvite, getTeamStats,
};
